package android.support.constraint;

public final class R {
    private R() {
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets = 2130903097;
        public static final int barrierDirection = 2130903098;
        public static final int chainUseRtl = 2130903131;
        public static final int constraintSet = 2130903154;
        public static final int constraint_referenced_ids = 2130903155;
        public static final int content = 2130903156;
        public static final int emptyVisibility = 2130903188;
        public static final int layout_constrainedHeight = 2130903258;
        public static final int layout_constrainedWidth = 2130903259;
        public static final int layout_constraintBaseline_creator = 2130903260;
        public static final int layout_constraintBaseline_toBaselineOf = 2130903261;
        public static final int layout_constraintBottom_creator = 2130903262;
        public static final int layout_constraintBottom_toBottomOf = 2130903263;
        public static final int layout_constraintBottom_toTopOf = 2130903264;
        public static final int layout_constraintCircle = 2130903265;
        public static final int layout_constraintCircleAngle = 2130903266;
        public static final int layout_constraintCircleRadius = 2130903267;
        public static final int layout_constraintDimensionRatio = 2130903268;
        public static final int layout_constraintEnd_toEndOf = 2130903269;
        public static final int layout_constraintEnd_toStartOf = 2130903270;
        public static final int layout_constraintGuide_begin = 2130903271;
        public static final int layout_constraintGuide_end = 2130903272;
        public static final int layout_constraintGuide_percent = 2130903273;
        public static final int layout_constraintHeight_default = 2130903274;
        public static final int layout_constraintHeight_max = 2130903275;
        public static final int layout_constraintHeight_min = 2130903276;
        public static final int layout_constraintHeight_percent = 2130903277;
        public static final int layout_constraintHorizontal_bias = 2130903278;
        public static final int layout_constraintHorizontal_chainStyle = 2130903279;
        public static final int layout_constraintHorizontal_weight = 2130903280;
        public static final int layout_constraintLeft_creator = 2130903281;
        public static final int layout_constraintLeft_toLeftOf = 2130903282;
        public static final int layout_constraintLeft_toRightOf = 2130903283;
        public static final int layout_constraintRight_creator = 2130903284;
        public static final int layout_constraintRight_toLeftOf = 2130903285;
        public static final int layout_constraintRight_toRightOf = 2130903286;
        public static final int layout_constraintStart_toEndOf = 2130903287;
        public static final int layout_constraintStart_toStartOf = 2130903288;
        public static final int layout_constraintTop_creator = 2130903289;
        public static final int layout_constraintTop_toBottomOf = 2130903290;
        public static final int layout_constraintTop_toTopOf = 2130903291;
        public static final int layout_constraintVertical_bias = 2130903292;
        public static final int layout_constraintVertical_chainStyle = 2130903293;
        public static final int layout_constraintVertical_weight = 2130903294;
        public static final int layout_constraintWidth_default = 2130903295;
        public static final int layout_constraintWidth_max = 2130903296;
        public static final int layout_constraintWidth_min = 2130903297;
        public static final int layout_constraintWidth_percent = 2130903298;
        public static final int layout_editor_absoluteX = 2130903300;
        public static final int layout_editor_absoluteY = 2130903301;
        public static final int layout_goneMarginBottom = 2130903302;
        public static final int layout_goneMarginEnd = 2130903303;
        public static final int layout_goneMarginLeft = 2130903304;
        public static final int layout_goneMarginRight = 2130903305;
        public static final int layout_goneMarginStart = 2130903306;
        public static final int layout_goneMarginTop = 2130903307;
        public static final int layout_optimizationLevel = 2130903310;

        private attr() {
        }
    }

    public static final class id {
        public static final int barrier = 2131230758;
        public static final int bottom = 2131230762;
        public static final int chains = 2131230772;
        public static final int dimensions = 2131230792;
        public static final int direct = 2131230793;
        public static final int end = 2131230798;
        public static final int gone = 2131230811;
        public static final int invisible = 2131230828;
        public static final int left = 2131230832;
        public static final int none = 2131230850;
        public static final int packed = 2131230855;
        public static final int parent = 2131230857;
        public static final int percent = 2131230860;
        public static final int right = 2131230866;
        public static final int spread = 2131230903;
        public static final int spread_inside = 2131230904;
        public static final int standard = 2131230908;
        public static final int start = 2131230909;
        public static final int top = 2131230928;
        public static final int wrap = 2131230943;

        private id() {
        }
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = {16842948, 16843039, 16843040, 16843071, 16843072, com.jds.binr.R.attr.barrierAllowsGoneWidgets, com.jds.binr.R.attr.barrierDirection, com.jds.binr.R.attr.chainUseRtl, com.jds.binr.R.attr.constraintSet, com.jds.binr.R.attr.constraint_referenced_ids, com.jds.binr.R.attr.layout_constrainedHeight, com.jds.binr.R.attr.layout_constrainedWidth, com.jds.binr.R.attr.layout_constraintBaseline_creator, com.jds.binr.R.attr.layout_constraintBaseline_toBaselineOf, com.jds.binr.R.attr.layout_constraintBottom_creator, com.jds.binr.R.attr.layout_constraintBottom_toBottomOf, com.jds.binr.R.attr.layout_constraintBottom_toTopOf, com.jds.binr.R.attr.layout_constraintCircle, com.jds.binr.R.attr.layout_constraintCircleAngle, com.jds.binr.R.attr.layout_constraintCircleRadius, com.jds.binr.R.attr.layout_constraintDimensionRatio, com.jds.binr.R.attr.layout_constraintEnd_toEndOf, com.jds.binr.R.attr.layout_constraintEnd_toStartOf, com.jds.binr.R.attr.layout_constraintGuide_begin, com.jds.binr.R.attr.layout_constraintGuide_end, com.jds.binr.R.attr.layout_constraintGuide_percent, com.jds.binr.R.attr.layout_constraintHeight_default, com.jds.binr.R.attr.layout_constraintHeight_max, com.jds.binr.R.attr.layout_constraintHeight_min, com.jds.binr.R.attr.layout_constraintHeight_percent, com.jds.binr.R.attr.layout_constraintHorizontal_bias, com.jds.binr.R.attr.layout_constraintHorizontal_chainStyle, com.jds.binr.R.attr.layout_constraintHorizontal_weight, com.jds.binr.R.attr.layout_constraintLeft_creator, com.jds.binr.R.attr.layout_constraintLeft_toLeftOf, com.jds.binr.R.attr.layout_constraintLeft_toRightOf, com.jds.binr.R.attr.layout_constraintRight_creator, com.jds.binr.R.attr.layout_constraintRight_toLeftOf, com.jds.binr.R.attr.layout_constraintRight_toRightOf, com.jds.binr.R.attr.layout_constraintStart_toEndOf, com.jds.binr.R.attr.layout_constraintStart_toStartOf, com.jds.binr.R.attr.layout_constraintTop_creator, com.jds.binr.R.attr.layout_constraintTop_toBottomOf, com.jds.binr.R.attr.layout_constraintTop_toTopOf, com.jds.binr.R.attr.layout_constraintVertical_bias, com.jds.binr.R.attr.layout_constraintVertical_chainStyle, com.jds.binr.R.attr.layout_constraintVertical_weight, com.jds.binr.R.attr.layout_constraintWidth_default, com.jds.binr.R.attr.layout_constraintWidth_max, com.jds.binr.R.attr.layout_constraintWidth_min, com.jds.binr.R.attr.layout_constraintWidth_percent, com.jds.binr.R.attr.layout_editor_absoluteX, com.jds.binr.R.attr.layout_editor_absoluteY, com.jds.binr.R.attr.layout_goneMarginBottom, com.jds.binr.R.attr.layout_goneMarginEnd, com.jds.binr.R.attr.layout_goneMarginLeft, com.jds.binr.R.attr.layout_goneMarginRight, com.jds.binr.R.attr.layout_goneMarginStart, com.jds.binr.R.attr.layout_goneMarginTop, com.jds.binr.R.attr.layout_optimizationLevel};
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
        public static final int ConstraintLayout_Layout_barrierDirection = 6;
        public static final int ConstraintLayout_Layout_chainUseRtl = 7;
        public static final int ConstraintLayout_Layout_constraintSet = 8;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids = 9;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight = 10;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth = 11;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintCircle = 17;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 56;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 57;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 58;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 59;
        public static final int[] ConstraintLayout_placeholder = {com.jds.binr.R.attr.content, com.jds.binr.R.attr.emptyVisibility};
        public static final int ConstraintLayout_placeholder_content = 0;
        public static final int ConstraintLayout_placeholder_emptyVisibility = 1;
        public static final int[] ConstraintSet = {16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843551, 16843552, 16843553, 16843554, 16843555, 16843556, 16843557, 16843558, 16843559, 16843560, 16843701, 16843702, 16843770, 16843840, com.jds.binr.R.attr.layout_constrainedHeight, com.jds.binr.R.attr.layout_constrainedWidth, com.jds.binr.R.attr.layout_constraintBaseline_creator, com.jds.binr.R.attr.layout_constraintBaseline_toBaselineOf, com.jds.binr.R.attr.layout_constraintBottom_creator, com.jds.binr.R.attr.layout_constraintBottom_toBottomOf, com.jds.binr.R.attr.layout_constraintBottom_toTopOf, com.jds.binr.R.attr.layout_constraintCircle, com.jds.binr.R.attr.layout_constraintCircleAngle, com.jds.binr.R.attr.layout_constraintCircleRadius, com.jds.binr.R.attr.layout_constraintDimensionRatio, com.jds.binr.R.attr.layout_constraintEnd_toEndOf, com.jds.binr.R.attr.layout_constraintEnd_toStartOf, com.jds.binr.R.attr.layout_constraintGuide_begin, com.jds.binr.R.attr.layout_constraintGuide_end, com.jds.binr.R.attr.layout_constraintGuide_percent, com.jds.binr.R.attr.layout_constraintHeight_default, com.jds.binr.R.attr.layout_constraintHeight_max, com.jds.binr.R.attr.layout_constraintHeight_min, com.jds.binr.R.attr.layout_constraintHeight_percent, com.jds.binr.R.attr.layout_constraintHorizontal_bias, com.jds.binr.R.attr.layout_constraintHorizontal_chainStyle, com.jds.binr.R.attr.layout_constraintHorizontal_weight, com.jds.binr.R.attr.layout_constraintLeft_creator, com.jds.binr.R.attr.layout_constraintLeft_toLeftOf, com.jds.binr.R.attr.layout_constraintLeft_toRightOf, com.jds.binr.R.attr.layout_constraintRight_creator, com.jds.binr.R.attr.layout_constraintRight_toLeftOf, com.jds.binr.R.attr.layout_constraintRight_toRightOf, com.jds.binr.R.attr.layout_constraintStart_toEndOf, com.jds.binr.R.attr.layout_constraintStart_toStartOf, com.jds.binr.R.attr.layout_constraintTop_creator, com.jds.binr.R.attr.layout_constraintTop_toBottomOf, com.jds.binr.R.attr.layout_constraintTop_toTopOf, com.jds.binr.R.attr.layout_constraintVertical_bias, com.jds.binr.R.attr.layout_constraintVertical_chainStyle, com.jds.binr.R.attr.layout_constraintVertical_weight, com.jds.binr.R.attr.layout_constraintWidth_default, com.jds.binr.R.attr.layout_constraintWidth_max, com.jds.binr.R.attr.layout_constraintWidth_min, com.jds.binr.R.attr.layout_constraintWidth_percent, com.jds.binr.R.attr.layout_editor_absoluteX, com.jds.binr.R.attr.layout_editor_absoluteY, com.jds.binr.R.attr.layout_goneMarginBottom, com.jds.binr.R.attr.layout_goneMarginEnd, com.jds.binr.R.attr.layout_goneMarginLeft, com.jds.binr.R.attr.layout_goneMarginRight, com.jds.binr.R.attr.layout_goneMarginStart, com.jds.binr.R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_alpha = 9;
        public static final int ConstraintSet_android_elevation = 22;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 20;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 19;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotation = 16;
        public static final int ConstraintSet_android_rotationX = 17;
        public static final int ConstraintSet_android_rotationY = 18;
        public static final int ConstraintSet_android_scaleX = 14;
        public static final int ConstraintSet_android_scaleY = 15;
        public static final int ConstraintSet_android_transformPivotX = 10;
        public static final int ConstraintSet_android_transformPivotY = 11;
        public static final int ConstraintSet_android_translationX = 12;
        public static final int ConstraintSet_android_translationY = 13;
        public static final int ConstraintSet_android_translationZ = 21;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_layout_constrainedHeight = 23;
        public static final int ConstraintSet_layout_constrainedWidth = 24;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 25;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
        public static final int ConstraintSet_layout_constraintBottom_creator = 27;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 29;
        public static final int ConstraintSet_layout_constraintCircle = 30;
        public static final int ConstraintSet_layout_constraintCircleAngle = 31;
        public static final int ConstraintSet_layout_constraintCircleRadius = 32;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 33;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 34;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 35;
        public static final int ConstraintSet_layout_constraintGuide_begin = 36;
        public static final int ConstraintSet_layout_constraintGuide_end = 37;
        public static final int ConstraintSet_layout_constraintGuide_percent = 38;
        public static final int ConstraintSet_layout_constraintHeight_default = 39;
        public static final int ConstraintSet_layout_constraintHeight_max = 40;
        public static final int ConstraintSet_layout_constraintHeight_min = 41;
        public static final int ConstraintSet_layout_constraintHeight_percent = 42;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 43;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 45;
        public static final int ConstraintSet_layout_constraintLeft_creator = 46;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 48;
        public static final int ConstraintSet_layout_constraintRight_creator = 49;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 50;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 51;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 52;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 53;
        public static final int ConstraintSet_layout_constraintTop_creator = 54;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 55;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 56;
        public static final int ConstraintSet_layout_constraintVertical_bias = 57;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 58;
        public static final int ConstraintSet_layout_constraintVertical_weight = 59;
        public static final int ConstraintSet_layout_constraintWidth_default = 60;
        public static final int ConstraintSet_layout_constraintWidth_max = 61;
        public static final int ConstraintSet_layout_constraintWidth_min = 62;
        public static final int ConstraintSet_layout_constraintWidth_percent = 63;
        public static final int ConstraintSet_layout_editor_absoluteX = 64;
        public static final int ConstraintSet_layout_editor_absoluteY = 65;
        public static final int ConstraintSet_layout_goneMarginBottom = 66;
        public static final int ConstraintSet_layout_goneMarginEnd = 67;
        public static final int ConstraintSet_layout_goneMarginLeft = 68;
        public static final int ConstraintSet_layout_goneMarginRight = 69;
        public static final int ConstraintSet_layout_goneMarginStart = 70;
        public static final int ConstraintSet_layout_goneMarginTop = 71;
        public static final int[] LinearConstraintLayout = {16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;

        private styleable() {
        }
    }
}
